# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'


jobs:
   # Run unit tests to make sure everything is 👍
   build:
     name: 'Build, Compile, Test and Linting'
    # Specify the OS we want the workflow to run on
     runs-on: ubuntu-latest
     defaults:
        run:
          shell: bash
          # Define the working directory for all run steps in the workflow
          working-directory: ./src
     strategy:
       matrix:
         node-version: [18.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

     steps:
    
     - uses: actions/checkout@v4
       name: 'Checkout repository'
      
      
     - name: Setup/Use Node with version ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
        
     - run: npm ci
       name: 'Install Dependencies'
      
     - run: npm run build --if-present
       name: 'Build and Compile'

     - name: 'Run the Test'
       run: npm run test

   
        
   # Run the linter to check for code style issues
   lint:
     #needs: build
     name: 'Run linter for code analysis'
     defaults:
       run:
         shell: bash
         # Define the working directory for all run steps in the workflow
         working-directory: ./src
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:    
     - uses: actions/checkout@v4
       name: 'Checkout repository'
    
     - name: 'Install Dependencies'
       run: npm install

     - name: 'Run Linter'
       run: npx standard -v



   docker:
     name: 'Build and Push Docker'
     needs: [build, lint]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
      
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

         
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

         
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

           
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
           push: true
           platforms: linux/amd64,linux/arm64,linux/386
           tags: hassanali70826/docker-nodejs-app:${{ steps.vars.outputs.tag }}    #${{ env.BRANCH }}
           #build-args: |
             #BRANCH=${{ env.BRANCH }}           
        
