name: Test Docker Build Push GHCR

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 10 * * *"
  push:
    branches:
      - "none"
    #tags:
      #- "v*.*.*"
  pull_request:
    branches:
      - "none"
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/halilili/docker-nodejs-sample/my-app   #${{ env.REGISTRY }}/${{ github.repository }}/${{ github.repository_name }}
          #ghcr.io/halilili/docker-nodejs-sample/my-app:latest
    
    
      - name: Build and push - with version
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
