name: Command-Push Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - none

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.platforms }}
        push: true
        outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-app:latest .
        docker push ghcr.io/${{ github.repository }}/my-app:latest
