name: Image Scanning With Synk

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'



env:
  #Use docker.io for Docker Hub
  # Use ghcr.io for Github container registry
  REGISTRY: ghcr.io
  # github.repository as owner-name/repo
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_IMAGE_TAG: ${{ github.ref == 'refs/heads/master' && 'prod-' || 'dev-' }}${{ github.sha }}
  GITHUB_REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
 docker:
     name: 'Build and Push Docker'
     #needs: [test-job, lint]
     runs-on: ubuntu-latest
     # remove the permission will lead to a Forbidden error 403
     permissions:
      contents: read
      packages: write
      id-token: write
     steps:
       - name: Checkout
         uses: actions/checkout@v3
      
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

         
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Login to GHCR
         if: github.event_name != 'pull_request'
         uses: docker/login-action@v3
         with:
           registry: ${{ env.GITHUB_REGISTRY }}
           username: ${{ github.repository_owner }} #OR  ${{ github.actor }}
           password: ${{ secrets.ACCESS_TOKEN }}

       - name: Build and push Docker image 🐳
         uses: docker/build-push-action@v3
         with:
           push: true
           tags: |
             ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}

 snyk:
    runs-on: ubuntu-latest
    needs: [ docker ]
    permissions:
     actions: read
     contents: read
     security-events: write
    steps:
    - uses: actions/checkout@v4
      name: Checkout 🛎️

      
    - name: Build a Docker image
      run: docker build -t ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }} .
      
    - name: Run Snyk to check/scan Docker image for vulnerabilities 🐳
      id: run-analysis
      # Snyk can be used to break the build when it detects vulnerabilities.
      # In this case we want to upload the issues to GitHub Code Scanning
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        # In order to use the Snyk Action you will need to have a Snyk API token.
        # See https://docs.snyk.io/integrations/ci-cd-integrations/github-actions-integration#getting-your-snyk-token
        # or you can sign up for free at https://snyk.io/login
        SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
      with:
        image: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
        args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif


    # Upload SARIF file to GitHub Code Scanning Alerts
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        #sarif_file: snyk.sarif
        sarif_file: ${{ steps.run-analysis.outputs.snyk.sarif }}
        

    # Upload SARIF file as an Artifact to download and view
    # - name: Upload SARIF as an Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: sarif-file
    #     path: ${{ steps.run-analysis.outputs.sarif }}
