name: Trivay Container Scanning/Build Push image

on:
  workflow_dispatch:
  push:
    branches:
      - none
    paths:
      - 'src/**'
  pull_request:
    branches:
      - none
    paths:
      - 'src/**'



env:
  # github.repository as owner-name/repo
  IMAGE_NAME: ${{ github.repository }}
  #Use docker.io for Docker Hub
  # Use ghcr.io for Github container registry
  REGISTRY: ghcr.io
  # Branch-Sha-short it will be generated below
  IMAGE_TAG: '' 


jobs:

  container_scanning:
       name: 'Trivy container scanning'
       runs-on: ubuntu-latest
       # remove the permission will lead to a Forbidden error 403
       permissions: 
        contents: read
        packages: write
        id-token: write
        actions: write
        
       steps:
         - name: Checkout
           uses: actions/checkout@v3
        
         
         - name: Login to Docker Hub
           if: github.event_name != 'pull_request'
           uses: docker/login-action@v3
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}

         - name: Declare/Set Image Tag
           shell: bash
           run: |
              echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/})-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        
         - name: Display Image Tag
           run: |
              echo "Image Tag: ${{ env.IMAGE_TAG }}"

         - name: Build a Docker image
           run: |
            docker build -t  docker.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }} .

     
         - name: Run Trivy vulnerability scanner
           uses: aquasecurity/trivy-action@master
           with:
            image-ref: 'docker.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}'
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH,MEDIUM'

         - name: Run Trivy vulnerability scanner for uploading
           uses: aquasecurity/trivy-action@master
           with:
             image-ref: 'docker.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}'
             format: 'json' #.sarif
             output: 'trivy-results.json' #.sarif
            
      
         - name: 'Upload SARIF file as an Artifact to download and view'
           uses: actions/upload-artifact@v3
           with:
             name: trivay-SARIF
             path: trivy-results.json #.sarif

 
  docker:
       name: 'Build and Push Docker'
       needs: [container_scanning]
       runs-on: ubuntu-latest
       # remove the permission will lead to a Forbidden error 403
       permissions: 
        contents: read
        packages: write
        id-token: write
        actions: write
       steps:
         - name: Checkout
           uses: actions/checkout@v3
        
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3
  
           
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
  
         - name: Login to GHCR
           if: github.event_name != 'pull_request'
           uses: docker/login-action@v3
           with:
             registry: ${{ env.REGISTRY }}
             username: ${{ github.repository_owner }} #OR  ${{ github.actor }}
             password: ${{ secrets.ACCESS_TOKEN }}

         - name: Declare/Set Image Tag
           shell: bash
           run: |
              echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/})-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        
         - name: Display Image Tag
           run: |
              echo "Image Tag: ${{ env.IMAGE_TAG }}"


         - name: 'To Lower Case '
           id: string
           uses: ASzc/change-string-case-action@v5
           with:
             string: ${{ github.repository_owner }}
        
          #we are using github.repository_owner instead of #github.actor
         - name: Build and push Docker image 🐳
           uses: docker/build-push-action@v3
           with:
             push: true
             tags: | #steps.string.outputs.lowercase
               ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}
  
